database:
  type: sqlite

sqlite:
  file: rpgroll.db

mysql:
  host: localhost
  port: 3306
  database: rpgroll
  username: root
  password: ""

postgresql:
  host: localhost
  port: 5432
  database: rpgroll
  username: postgres
  password: ""
