name: RPGRoll-Fishing
version: 1.0.0
main: com.sack.rpgroll.fishing.FishingPlugin
api-version: "26.1.1"
author: Sack
description: Pesca como profesión completa — cientos de especies configurables, cañas/carnadas, minijuego vanilla o RPG, tesoros/basura, peces legendarios y enciclopedia de capturas.
depend: [RPGRoll]
softdepend: [RPGRoll-FX, RPGRoll-Effects, RPGRoll-Seasons, SackResourcePack]

permissions:
  rpgrollfishing.admin.*:
    description: Acceso completo a comandos administrativos de Fishing Studio
    default: op
  rpgrollfishing.use:
    description: Uso básico de pesca (enciclopedia, estadísticas)
    default: true
