ALTER TABLE players ADD COLUMN IF NOT EXISTS unspent_stat_points INTEGER NOT NULL DEFAULT 0;

ALTER TABLE player_stats ADD COLUMN IF NOT EXISTS max_health INTEGER NOT NULL DEFAULT 100;

ALTER TABLE player_stats ADD COLUMN IF NOT EXISTS current_health INTEGER NOT NULL DEFAULT 100;

ALTER TABLE player_stats ADD COLUMN IF NOT EXISTS max_mana INTEGER NOT NULL DEFAULT 100;

ALTER TABLE player_stats ADD COLUMN IF NOT EXISTS current_mana INTEGER NOT NULL DEFAULT 100;
