name: RPGRoll-Enchantments
version: 1.0.0
main: com.sack.rpgroll.enchantments.EnchantmentsPlugin
api-version: "26.1.1"
author: Sack
description: Sistema de encantamientos personalizados basado en componentes (triggers, condiciones y efectos) para RPGRoll
depend: [RPGRoll]
softdepend: [RPGRoll-FX, PlaceholderAPI]

permissions:
  rpgrollenchantments.admin.*:
    description: Acceso completo a comandos de encantamientos
    default: op
