# Dispara el efecto 'maremoto' de RPGRoll-FX además de su daño.
# El efecto es lo que lo hace notarse; el daño es lo que lo hace valer.
id: maremoto
display-name: "&3Maremoto"
rarity: EPIC
max-level: 3

categories:
  - TRIDENT

trigger:
  - PLAYER_ATTACK

levels:
  1:
    power: 4
  2:
    power: 6
  3:
    power: 9

effects:
  - type: PARTICLES
    effect-id: maremoto
  - type: DAMAGE
    amount: "{power}"
    apply-to: target
