# Dispara el efecto 'vendaval' de RPGRoll-FX además de su daño.
# El efecto es lo que lo hace notarse; el daño es lo que lo hace valer.
id: vendaval
display-name: "&fVendaval"
rarity: UNCOMMON
max-level: 3

categories:
  - BOOTS

trigger:
  - PLAYER_JUMP

levels:
  1:
    power: 3
  2:
    power: 5
  3:
    power: 7

effects:
  - type: PARTICLES
    effect-id: vendaval
  - type: DAMAGE
    amount: "{power}"
    apply-to: target
