id: miner_pickaxe
category: tools
material: IRON_PICKAXE
display-name: "&ePico del Minero"
lore:
  - "&7Extrae minerales más rápido que cualquier otro."
rarity: UNCOMMON

stats:
  mining_speed: 25

durability:
  max: 400
  repairable: true
  degrade-per-use: 1
  auto-repair-per-minute: 1

triggers:
  BLOCK_BREAK:
    - type: PARTICLE
      particle: CRIT
      count: 4

economy:
  sell: 80
