ALTER TABLE players ADD COLUMN unspent_stat_points INTEGER NOT NULL DEFAULT 0;

ALTER TABLE player_stats ADD COLUMN max_health INTEGER NOT NULL DEFAULT 100;

ALTER TABLE player_stats ADD COLUMN current_health INTEGER NOT NULL DEFAULT 100;

ALTER TABLE player_stats ADD COLUMN max_mana INTEGER NOT NULL DEFAULT 100;

ALTER TABLE player_stats ADD COLUMN current_mana INTEGER NOT NULL DEFAULT 100;
